name: Deploy to Vercel on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "https://api.vercel.com/v13/deployments" \
            -H "Authorization: Bearer $VERCEL_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "easydev",
              "project": "'$VERCEL_PROJECT_ID'",
              "target": "production",
              "gitSource": {
                "type": "github",
                "repo": "'${{ github.repository }}'",
                "ref": "'${{ github.ref_name }}'"
              },
              "env": {
                "NEXT_PUBLIC_APP_VERSION": "'${{ github.ref_name }}'"
              }
            }'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
